### ISSUE TITLE
The website isn't working

### ISSUE THREAD

**Issue by dpgil** [jbadlato/Markov-Rankings#203]
the website isn't working

this is blocking my workflow
cc: @rniemo

**Comment by rniemo** [comment]
Thanks for looping me in Dan.

Wanted to chime in here -- this is a pretty urgent situation for us, as our business model relies on a consistent stream of Markov rankings, which are immediately piped into a Google Slides presentation and shipped off to leadership. They use these presentations to decide how to manage billions of dollars worth of assets. We've found this approach to be an above average strategy compared to the rest of our Fortune 500 peers. Back to the point -- without this site our company will tank. Is there anyway to bump up the priority of this from "high" to something like "rly high" or "super duper large" or like "mega ginormous"?

**Comment by dpgil** [comment]
@rniemo i went ahead and updated the priority,.... let me know what you think........
