### ISSUE TITLE
FBS Rankings were incorrect this past season

### ISSUE THREAD

**Issue by rniemo** [jbadlato/Markov-Rankings#204]
Was just looking at my favorite twitter account, MarkovRankings, and noticed something strange with all the college football rankings. I was surprised no one caught this before (hello? any staging environments in this project??), but in the rankings sometimes the number one spot is not occupied by The Ohio State University??? Ya, that's a pretty huge oversight.... anyway. Is there a third-party group holding the developers accountable for this mistake or smthn bc this is not what MY tax dollars should be used on. i am a taxpayer

actual behavior: https://imgur.com/cM26fye
expected behavior: https://imgur.com/QueB7W8

cc @dpgil , if you bring up 2014 i'm deleting this issue

**Comment by jbadlato** [comment]
Thank you for bringing this to our attention.  We met with all the relevant stakeholders and came up with a solution we hope will fit your use case.  We have assigned a developer to work on this full-time.  Bear with us, we hope to ship this as soon as humanly possible.  In the meantime, if you have any further input, please direct your suggestions to @dpgil as he will be spearheading this improvement for the foreseeable future.
